<?php

declare(strict_types=1);

use Yiisoft\FormModel\Field;
use Yiisoft\Html\Html;
use Yiisoft\Html\Tag\Form;

/*
 * @var App\Invoice\Entity\CustomField $custom_field
 * @var App\Invoice\CustomValue\CustomValueForm $form
 * @var App\Widget\Button $button
 * @var Yiisoft\Translator\TranslatorInterface $translator
 * @var Yiisoft\Router\FastRoute\UrlGenerator $urlGenerator
 * @var string $actionName
 * @var string $csrf
 * @var string $custom_field_id
 * @psalm-var array<string, Stringable|null|scalar> $actionArguments
 * @psalm-var array<string,list<string>> $errors
 */
?>
    
<?php echo Form::tag()
    ->post($urlGenerator->generate($actionName, $actionArguments))
    ->enctypeMultipartFormData()
    ->csrf($csrf)
    ->id('CustomValueForm')
    ->open();
?> 

<?php echo Html::openTag('div'); ?>
<?php echo Html::openTag('div', ['class' => 'container py-5 h-100']); ?>
<?php echo Html::openTag('div', ['class' => 'row d-flex justify-content-center align-items-center h-100']); ?>
<?php echo Html::openTag('div', ['class' => 'col-12 col-md-8 col-lg-6 col-xl-8']); ?>
<?php echo Html::openTag('div', ['class' => 'card border border-dark shadow-2-strong rounded-3']); ?>
    <?php echo Html::openTag('div', ['class' => 'card-header']); ?>
        <?php echo Html::openTag('h1', ['class' => 'fw-normal h3 text-center']); ?>
        <?php echo $translator->translate('custom.values.new'); ?>
        <?php echo Html::closeTag('h1'); ?>        
    <?php echo Html::closeTag('div'); ?>

    <?php echo Html::openTag('div', ['id' => 'content']); ?>

        <?php echo Html::openTag('div', ['class' => 'row']); ?>
            <?php echo Html::openTag('div', ['class' => 'col-xs-12 col-md-6 col-md-offset-3']); ?>
                <?php echo Field::errorSummary($form)
            ->errors($errors)
            ->header($translator->translate('custom.value.error.summary'))
                    // if the value is left blank the 'Value cannot be blank' message will appear
            ->onlyProperties(...['value'])
            ->onlyCommonErrors();
?>

                <?php $alpha = str_replace('-', '_', strtolower($custom_field->getType())); ?>
                <?php // Type eg. Boolean, Single Choice, Multiple Choice and Label eg. My new Field,
       // belong to the Field Entity?> 
                <?php echo Html::openTag('div', ['class' => 'form-group']); ?>
                    <?php echo Html::openTag('label', ['for' => 'label']); ?>
                        <?php echo $translator->translate('field'); ?>
                    <?php echo Html::closeTag('label'); ?>
                    <?php echo Html::openTag('input', [
                        'class'    => 'form-control',
                        'disabled' => 'disabled',
                        'id'       => 'label',
                        'value'    => Html::encode($custom_field->getLabel() ?? ''),
                    ]);
?>
                <?php echo Html::closeTag('div'); ?>
    
                <?php echo Html::openTag('div', ['class' => 'form-group']); ?>
                    <?php echo Html::openTag('label', ['for' => 'label']); ?>
                        <?php echo $translator->translate('type'); ?>
                    <?php echo Html::closeTag('label'); ?>
                    <?php echo Html::openTag('input', [
                        'class'    => 'form-control',
                        'disabled' => 'disabled',
                        'id'       => 'type',
                        'value'    => Html::encode($translator->translate(''.$alpha.'')),
                    ]);
?>
                <?php echo Html::closeTag('div'); ?>
    
                <?php // Custom Value Form: (1) The two hidden fields
  //                    (2) The value field where new data will be entered?>
                <?php echo Html::openTag('div', ['class' => 'form-group']); ?>
                    <?php echo Field::hidden($form, 'custom_field_id')
      ->addInputAttributes([
          'class' => 'form-control',
          'id'    => 'custom_field_id'])
      ->value($custom_field->getId())
      ->hideLabel();
?>  
                <?php echo Html::closeTag('div'); ?>
    
                <?php // The id here is generated by the new CustomValueForm(new CustomValue); function
    // the id from the new CustomValue entity that is generated?>
                <?php echo Html::openTag('div', ['class' => 'form-group']); ?>
                    <?php echo Field::hidden($form, 'id')
        ->addInputAttributes([
            'class' => 'form-control',
            'id'    => 'id'])
        ->value(Html::encode($form->getId() ?? ''))
        ->hideLabel();
?>    
                <?php echo Html::closeTag('div'); ?>

                <?php echo Html::openTag('div', ['class' => 'form-group']); ?>
                    <?php echo Field::text($form, 'value')
                    ->addInputAttributes([
                        'class' => 'form-control',
                        'id'    => 'value'])
                    ->value(Html::encode($form->getValue() ?? ''));
?>
                <?php echo Html::closeTag('div'); ?>
            <?php echo Html::closeTag('div'); ?>
        <?php echo Html::closeTag('div'); ?>
        <?php echo $button::backSave(); ?>
    <?php echo Html::closeTag('div'); ?>
<?php echo Html::closeTag('div'); ?>
<?php echo Html::closeTag('div'); ?>
<?php echo Html::closeTag('div'); ?>
<?php echo Html::closeTag('div'); ?>
<?php echo Html::closeTag('div'); ?>
<?php echo Form::tag()->close(); ?>
