sonar.projectKey=rossaddison_invoice
sonar.organization=rossaddison
sonar.projectName=Invoice Application
sonar.projectVersion=1.0
sonar.sourceEncoding=UTF-8

# Sources and tests
sonar.sources=src,config,public
sonar.tests=Tests
sonar.php.coverage.reportPaths=coverage.xml
sonar.php.tests.reportPath=test-results.xml
sonar.exclusions=vendor/**,runtime/**,public/assets/**,nbproject/**,docker/**,src/Invoice/Asset/**,e.g.ini/**,resources/messages/**

# Language versions
sonar.php.version=8.4

sonar.issue.ignore.multicriteria=e1,e2,e3,e4
sonar.issue.ignore.multicriteria.e1.ruleKey=php:S116
sonar.issue.ignore.multicriteria.e1.resourceKey=**/*.php
sonar.issue.ignore.multicriteria.e2.ruleKey=php:S1068
sonar.issue.ignore.multicriteria.e2.resourceKey=**/*.php
sonar.issue.ignore.multicriteria.e4.ruleKey=php:S1125
sonar.issue.ignore.multicriteria.e4.resourceKey=**/*.php
sonar.issue.ignore.multicriteria.e3.ruleKey=php:S1192
sonar.issue.ignore.multicriteria.e3.resourceKey=**/*.php
sonar.cpd.exclusions=src/Invoice/Helpers/Peppol/**,src/Invoice/Helpers/StoreCove/StoreCoveArrays.php,src/Widget/SalesOrderToolbar.php
sonar.javascript.lcov.reportPaths=coverage/lcov.info
