<?php

declare(strict_types=1);

use Yiisoft\Html\Html;
use Yiisoft\Router\UrlGeneratorInterface;

/**
 * @var int $fontSize
 * @var UrlGeneratorInterface $urlGenerator
 */

$settingUrl = $urlGenerator->generate(
    'setting/tabIndex',
    [],
    ['active' => 'invoices'],
    'settings[homecare_auto_invoice_enabled]',
);
?>

<div style="font-size: <?= $fontSize ?: 16; ?>px;">

<h6 id="what-is">What is Homecare Cleaning Auto Invoice?</h6>
<p>
    Homecare Cleaning Auto Invoice is a public, unauthenticated QR-scan facility for
    home-care clients. When a client scans their personal QR code, the system checks
    whether they are eligible for an automatically generated invoice: their most
    recently paid invoice must contain at least one Service-type product, and no
    invoice &mdash; paid or not &mdash; may have been raised since that payment. When
    eligible, a new invoice is generated by copying the items and amounts from that
    invoice, removing the need to manually re-create a recurring cleaning invoice.
</p>
<p>
    See <code>src/Invoice/Inv/HomeCareCleaningEligibilityService.php</code> for the
    eligibility rules and <code>src/Invoice/Inv/Trait/HomeCareScan.php</code> for the
    scan endpoint.
</p>

<h6 id="where-is-the-setting">Where is the setting?</h6>
<p>
    The <b>Enable Home Care QR Auto-Invoice</b> switch is off by default. Turn it on
    at
    <a href="<?= Html::encode($settingUrl) ?>">Settings &rarr; Invoices &rarr; Enable Home Care QR Auto-Invoice</a>.
</p>

</div>
