<?php

declare(strict_types=1);

namespace App\Invoice\Enum;

// Note: this enum format is simply used for type-safe comparisons in code,
// same convention as ProductType — the value is stored as a plain string
// column on StockMovement, not as a native enum column.

enum StockMovementType: string
{
    // Stock leaving on a paid invoice/order (backend or webshop). Written
    // when an Inv reaches status_id 4 (paid) — never at draft or sent, a
    // sent-but-unpaid invoice does not commit stock. See
    // App\Infrastructure\Persistence\StockMovement\StockMovement.
    case Sale = 'sale';

    // Stock returning after a paid invoice is cancelled/refunded/credited.
    case Return = 'return';

    // Stock arriving from a supplier.
    case Receipt = 'receipt';

    // Manual correction outside of a sale/receipt/return — e.g. damage,
    // write-off, or a one-off admin fix.
    case Adjustment = 'adjustment';

    // Correction generated by finalizing a StockTake (physical count vs
    // system quantity). Not yet built — reserved for that phase.
    case StocktakeCorrection = 'stocktake_correction';
}
