<?php

declare(strict_types=1);

namespace Tests\Acceptance;

use OTPHP\TOTP;
use Symfony\Component\Clock\NativeClock;
use Tests\Support\AcceptanceTester;

/**
 * Genuine, unmocked, end-to-end Peppol happy-path test: seeds a real
 * domain fixture (App\Invoice\Peppol\Console\SeedPeppolHappyPathFixtureCommand),
 * logs in through the app's real HTTP + mandatory-2FA flow, hits the real
 * GET /invoice/inv/peppol/{id} route, and asserts the generated UBL XML
 * passes real Peppol/EN16931 validation (PeppolValidator, backed by the
 * genuine PEPPOL-EN16931-UBL.sch Schematron ruleset in resources/peppol/)
 * with zero errors -- something no amount of Testo/Mockery unit testing
 * can substitute for. This is the outcome of a chain of real Peppol UBL
 * generation bugs found and fixed via exactly this route this session
 * (see PRs #1151, #1153, #1155, #1156, and the Inv-hard-delete fix that
 * unblocked --cleanup below).
 *
 * Uses a dedicated test admin account (login below) rather than a real
 * one, so this can run unattended in CI: 2FA is mandatory for every admin
 * account regardless of the global enable_tfa setting (see
 * App\User\Console\CreateCommand's own docblock), and a live human-read
 * TOTP code obviously can't be part of an automated test run. This
 * account's TOTP secret was generated by this test's own one-time setup
 * flow (GET /showSetup, which returns a fresh secret in the page itself)
 * -- not extracted from anyone else's account -- so it's safe to commit
 * here and reuse on every run.
 *
 * Seeding/cleanup go through the Cli module (runShellCommand()/
 * grabShellOutput()), not raw shell_exec -- forbidden by this project's
 * own Psalm security rules, and Cli is Codeception's own sanctioned way
 * to invoke console commands from a test (see Tests/Cli/ConsoleCest.php
 * for the established pattern this follows).
 */
final class PeppolHappyPathCest
{
    private const string LOGIN = 'peppoltest';
    private const string PASSWORD = 'peppoltest123';
    // Provisioned once via this account's own /showSetup + /verifySetup
    // flow (see class docblock) -- not a secret belonging to any real user.
    private const string TOTP_SECRET =
        '76CWXHQU7J52QI2SVZA4QL4WBLYKJE4ZWTZNPVXOMJKLBUTN5IW2X3Y33XJXJBJJDK3A3YINC23WU2M6CTH552QLHUCW3TJBND7T2EA';

    private int $seededInvId = 0;

    private function yiiCommand(): string
    {
        return dirname(__DIR__, 2) . '/yii';
    }

    private function seedFixture(AcceptanceTester $I): int
    {
        $I->runShellCommand($this->yiiCommand() . ' peppol/seed-happy-path-fixture');
        $output = $I->grabShellOutput();
        if (preg_match('/INV_ID=(\d+)/', $output, $m) !== 1) {
            throw new \RuntimeException('Failed to seed Peppol fixture -- console output: ' . $output);
        }
        return (int) $m[1];
    }

    private function currentTotpCode(): string
    {
        // Passing a real clock avoids otphp's own "$clock will become
        // mandatory in 12.0.0" deprecation notice (this project's own
        // production TOTP::create() calls, in TwoFactorAuth.php, already
        // carry this same pre-existing notice -- out of scope to fix
        // there as a side effect of this test, but nothing stops this
        // test's own call from being clean).
        return TOTP::create(self::TOTP_SECRET, clock: new NativeClock())->now();
    }

    public function _before(AcceptanceTester $I): void
    {
        $this->seededInvId = $this->seedFixture($I);
    }

    public function _after(AcceptanceTester $I): void
    {
        if ($this->seededInvId > 0) {
            $I->runShellCommand(
                $this->yiiCommand() . ' peppol/seed-happy-path-fixture --cleanup=' . $this->seededInvId,
                false, // don't fail the test over a teardown-only step
            );
        }
    }

    public function testFixtureInvoicePassesRealPeppolValidationWithZeroErrors(AcceptanceTester $I): void
    {
        $I->amGoingTo('log in as the dedicated Peppol test account');
        $I->amOnPage('/login');
        $I->fillField('Login[login]', self::LOGIN);
        $I->fillField('Login[password]', self::PASSWORD);
        $I->click('Submit', '#loginForm');

        $I->expectTo('be routed into the mandatory 2FA verification step');
        $I->seeInCurrentUrl('/verifyLogin');
        $I->fillField('code', $this->currentTotpCode());
        $I->click('Submit', '#twoFactorAuthenticationVerfiyForm');

        $I->expectTo('be fully authenticated');
        $I->dontSeeInCurrentUrl('/login');
        $I->dontSeeInCurrentUrl('/verifyLogin');

        $I->amGoingTo('generate the seeded fixture invoice\'s Peppol UBL XML');
        $I->amOnPage('/invoice/inv/peppol/' . $this->seededInvId);

        $I->expectTo('see the generated XML with no validation-errors section at all');
        // peppolStreamOutput() (App\Invoice\Inv\Trait\Peppol) only renders
        // the bare <pre>XML</pre> -- skipping the "peppolerrors" view
        // entirely -- when PeppolValidator::validate() returns true, i.e.
        // zero errors. Asserting the absence of that view's own heading is
        // therefore a direct check on real Peppol/EN16931 validation
        // passing, not just on the request not crashing.
        $I->dontSee('PEPPOL Validation Errors');
        $I->see('<Invoice');
        $I->see('<cbc:ID>' . $this->seededInvId . '</cbc:ID>');
    }
}
