<?php

declare(strict_types=1);

namespace App\Auth\Trait;

use App\Auth\Form\TwoFactorAuthenticationSetupForm;
use App\Auth\Form\TwoFactorAuthenticationVerifyLoginForm;
use App\Infrastructure\Persistence\User\User;
use App\Invoice\UserInv\UserInvRepository;
use App\User\UserRepository;
use OTPHP\TOTP;
use Psr\Http\Message\ResponseInterface;
use Psr\Http\Message\ServerRequestInterface;
use Psr\Log\LogLevel;
use Yiisoft\Http\Method;
use Yiisoft\Json\Json;
use Yiisoft\Security\TokenMask;
use Yiisoft\Translator\TranslatorInterface;

trait TwoFactorAuth
{
    /**
     * Step 1: Download Aegis 2FA app onto your mobile
     * Step 2: Add a new Qr code by pressing the plus sign at the bottom right corner
     * Step 3: Scan the Qr code generated by the setup form with your mobile
     * Step 4: Enter the TOTP (Timed One Time Password) within the limited time
     */
    public function showSetup(
        TranslatorInterface $translator,
        UserRepository $userRepository,
    ): ResponseInterface {
        $userId = (int) $this->session->get('pending_2fa_user_id');
        $user = $userRepository->findById($userId);
        $email = $user->getEmail();
        if (strlen($email) > 0) {
            $totp = TOTP::create();
            /** @var non-empty-string $email */
            $totp->setLabel($email);
            $secret = $totp->getSecret();
            $this->session->set('2fa_temp_secret', $secret);
            $qrContent = $totp->getProvisioningUri();
            $qrDataUri = $this->tfaHelper->generateQrDataUri($qrContent);
            $form = new TwoFactorAuthenticationSetupForm($translator);
            return $this->webViewRenderer->render('setup', [
                'class' => $this->classList(),
                'qrDataUri' => $qrDataUri,
                'totpSecret' => $secret,
                'error' => '',
                'formModel' => $form,
            ]);
        }
        return $this->redirectToOneTimePasswordError();
    }

    /**
     * Related logic: see src\Auth\Asset\rebuild\js\keypad_copy_to_clipboard.js
     */
    public function ajaxShowSetup(ServerRequestInterface $request): ResponseInterface
    {
        $params = $request->getQueryParams();
        $parameters = [
            'success' => 1,
            'secretInputType' => $params['secretInputType'],
            'eyeIconClass' => $params['eyeIconClass'],
        ];
        return $this->factory->createResponse(Json::encode($parameters));
    }

    /**
     * On successful setup, the User table's 'tfa_enabled' field will be set to
     * true and the totp_secret will be set for function's verifyLogin's use.
     * Verify 2FA code during setup process.
     */
    public function verifySetup(
        ServerRequestInterface $request,
        TranslatorInterface $translator,
        UserRepository $userRepository,
    ): ResponseInterface {
        $clientIp = $this->secHelper->getClientIpAddress($request);
        $rateLimitKey = 'auth_setup_' . hash('sha256', $clientIp);

        $response = $this->redirectToOneTimePasswordError();
        if ($this->secHelper->checkRateLimit($rateLimitKey)) {
            $pendingUserId = (int) $this->session->get('pending_2fa_user_id');
            $body = $request->getParsedBody() ?? [];
            if (is_array($body)) {
                $result = $this->processSetupVerification(
                    $pendingUserId, $body, $translator, $userRepository);
                if ($result !== null) {
                    $response = $result;
                }
            }
        } else {
            $this->logger->log(LogLevel::WARNING,
                'Rate limit reached for 2FA setup from IP: ' . $clientIp);
        }
        return $response;
    }

    /**
     * Verify 2FA code during login process if the User:tfa_enabled field is true.
     * Disable TFA after verification for additional layer of security.
     */
    public function verifyLogin(
        ServerRequestInterface $request,
        TranslatorInterface $translator,
        UserRepository $userRepository,
    ): ResponseInterface {
        $vuid = (int) $this->session->get('verified_2fa_user_id');
        $form = new TwoFactorAuthenticationVerifyLoginForm($translator);
        $codes = [];
        $user = $userRepository->findById($vuid);
        // Only display the recovery codes once i.e. if the user does not have any
        if (!$this->recoveryCodeService->userHasBackupCodes($user)) {
            $codes = $this->tfaHelper->generateBackupRecoveryCodes($user);
            $this->session->set('backup_recovery_codes', $codes);
        }
        if ($this->session->get('regenerate_codes')) {
            $this->tfaHelper->removeBackupRecoveryCodes($user);
            $codes = $this->tfaHelper->generateBackupRecoveryCodes($user);
            $this->session->set('backup_recovery_codes', $codes);
            $this->session->set('regenerate_codes', false);
        }
        $parameters = [
            'title' => $translator->translate('two.factor.authentication.form.verify.login'),
            'actionName' => 'auth/verifyLogin',
            'actionArguments' => [],
            'errors' => [],
            'error' => '',
            'formModel' => $form,
            // empty $codes => show button to regenerate
            'codes' => $codes,
        ];
        $response = null;
        if ($request->getMethod() === Method::POST) {
            $response = $this->handleVerifyLoginPost(
                $request, $translator, $userRepository, $vuid, $form, $codes);
        }
        return $response ?? $this->webViewRenderer->render('verify', $parameters);
    }

    private function processSetupVerification(
        int $pendingUserId,
        array $body,
        TranslatorInterface $translator,
        UserRepository $userRepository,
    ): ?ResponseInterface {
        $tfa = 'two.factor.authentication';
        $inputCode = $this->tfaHelper->sanitizeAndValidateCode($body['code'] ?? '');
        if ($inputCode === null || $pendingUserId <= 0) {
            return null;
        }
        $user = $userRepository->findById($pendingUserId);
        /** @var mixed $tempSecretRaw */
        $tempSecretRaw = $this->session->get('2fa_temp_secret');
        $tempSecret = (is_string($tempSecretRaw) && $tempSecretRaw !== '')
            ? $tempSecretRaw : null;
        if ($tempSecret === null) {
            $error = $translator->translate($tfa . '.no.secret.generated');
        } elseif (!$this->tfaHelper->isValidTotpCode($inputCode)) {
            $error = $translator->translate($tfa . '.invalid.code.format');
        } else {
            $result = $this->verifySetupTotp(
                $inputCode, $tempSecret, $pendingUserId, $user, $userRepository, $translator);
            if ($result === null) {
                return $this->webService->getRedirectResponse('auth/verifyLogin');
            }
            $error = $result;
        }
        return $this->renderSetupWithError($error, $tempSecret, $user, $translator);
    }

    /**
     * @param non-empty-string $tempSecret
     */
    private function verifySetupTotp(
        string $inputCode,
        string $tempSecret,
        int $pendingUserId,
        User $user,
        UserRepository $userRepository,
        TranslatorInterface $translator,
    ): ?string {
        $totp = TOTP::create($tempSecret);
        if ($totp->verify($inputCode)) {
            $user->setTotpSecret($tempSecret);
            $user->set2FAEnabled(true);
            $userRepository->save($user);
            $this->session->remove('2fa_temp_secret');
            $this->session->remove('pending_2fa_user_id');
            // Regenerate session ID on successful setup
            $this->session->regenerateId();
            $this->session->set('verified_2fa_user_id', $pendingUserId);
            return null;
        }
        $tfa = 'two.factor.authentication';
        return $translator->translate(
            $this->sR->getSetting('enable_tfa_with_disabling') == '1'
                ? $tfa . '.attempt.failure.must.setup'
                : $tfa . '.attempt.failure'
        );
    }

    private function renderSetupWithError(
        string $error,
        ?string $tempSecret,
        User $user,
        TranslatorInterface $translator,
    ): ResponseInterface {
        /** @var non-empty-string $safeSecret */
        $safeSecret = $tempSecret ?? TOTP::create()->getSecret();
        $totp = TOTP::create($safeSecret);
        $userEmail = $user->getEmail();
        if ($userEmail !== '') {
            $totp->setLabel($userEmail);
        }
        $qrContent = $totp->getProvisioningUri();
        $qrDataUri = $this->tfaHelper->generateQrDataUri($qrContent);
        $form = new TwoFactorAuthenticationSetupForm($translator);
        return $this->webViewRenderer->render('setup', [
            'class' => $this->classList(),
            'qrDataUri' => $qrDataUri,
            'totpSecret' => $totp->getSecret(),
            'error' => $error,
            'formModel' => $form,
        ]);
    }

    private function handleVerifyLoginPost(
        ServerRequestInterface $request,
        TranslatorInterface $translator,
        UserRepository $userRepository,
        int $vuid,
        TwoFactorAuthenticationVerifyLoginForm $form,
        array $codes,
    ): ResponseInterface {
        $tfa = 'two.factor.authentication';
        $clientIp = $this->secHelper->getClientIpAddress($request);
        $rateLimitKey = 'auth_verify_' . hash('sha256', $clientIp);
        /** Related logic: see config/web/di/rate-limit.php */
        if (!$this->secHelper->checkRateLimit($rateLimitKey)) {
            $this->logger->log(LogLevel::WARNING,
                'Rate limit reached for 2FA verification from IP: ' . $clientIp);
            return $this->webViewRenderer->render('verify', [
                'error' => $translator->translate($tfa . '.rate.limit.reached'),
                'formModel' => $form,
                'codes' => $codes,
            ]);
        }
        $body = $request->getParsedBody();
        $inputCode = is_array($body)
            ? $this->tfaHelper->sanitizeAndValidateCode($body['code'] ?? '')
            : null;
        if (null === $inputCode || $vuid <= 0) {
            return $this->webViewRenderer->render('verify', [
                'error' => $translator->translate($tfa . '.attempt.failure'),
                'formModel' => $form,
                'codes' => $codes,
            ]);
        }
        return $this->verifyLoginCode($inputCode, $vuid, $userRepository, $translator, $form, $codes);
    }

    private function verifyLoginCode(
        string $inputCode,
        int $vuid,
        UserRepository $userRepository,
        TranslatorInterface $translator,
        TwoFactorAuthenticationVerifyLoginForm $form,
        array $codes,
    ): ResponseInterface {
        $tfa = 'two.factor.authentication';
        $user = $userRepository->findById($vuid);
        $totpSecretRaw = $user->getTotpSecret();
        $totpSec = (is_string($totpSecretRaw) && $totpSecretRaw !== '')
            ? $totpSecretRaw : null;
        if ($totpSec !== null && $this->tfaHelper->isValidTotpCode($inputCode)) {
            $response = $this->tryTotpLogin($inputCode, $totpSec, $vuid, $user, $userRepository);
            $error = ($response === null) ? $translator->translate($tfa . '.invalid.totp.code') : '';
        } else {
            $response = $this->tryBackupCodeLogin($inputCode, $totpSec, $vuid, $user);
            $error = ($response === null)
                ? $translator->translate($tfa . '.invalid.backup.recovery.code') : '';
        }
        if ($response !== null) {
            return $response;
        }
        return $this->webViewRenderer->render('verify', [
            'error' => $error,
            'formModel' => $form,
            'codes' => $codes,
        ]);
    }

    /**
     * @param non-empty-string $totpSec
     */
    private function tryTotpLogin(
        string $inputCode,
        string $totpSec,
        int $vuid,
        User $user,
        UserRepository $userRepository,
    ): ?ResponseInterface {
        $totp = TOTP::create($totpSec);
        if (!$totp->verify($inputCode)) {
            return null;
        }
        if ($this->sR->getSetting('enable_tfa_with_disabling') == '1') {
            $user->setTotpSecret('');
            $user->set2FAEnabled(false);
            $userRepository->save($user);
        }
        // Regenerate session ID on successful authentication
        $this->session->regenerateId();
        $this->secHelper->remSessTempsPermitEntryBase($vuid);
        /**
         * Related logic: HmrcController function fphValidate
         */
        $tokenApplySec = TokenMask::apply($totpSec);
        $this->session->set('otp', $inputCode);
        $this->session->set('otpRef', $tokenApplySec);
        return $this->redirectToInvoiceIndex();
    }

    private function tryBackupCodeLogin(
        string $inputCode,
        ?string $totpSec,
        int $vuid,
        User $user,
    ): ?ResponseInterface {
        if ($totpSec === null
                || !$this->recoveryCodeService->validateAndMarkCodeAsUsed($user, $inputCode)) {
            return null;
        }
        $tokenApplySec = TokenMask::apply($totpSec);
        $this->secHelper->remSessTempsPermitEntryBase($vuid);
        $this->session->set('otp', $inputCode);
        $this->session->set('otpRef', $tokenApplySec);
        return $this->redirectToInvoiceIndex();
    }

    private function redirectToOneTimePasswordError(): ResponseInterface
    {
        return $this->webService->getRedirectResponse('site/onetimepassworderror',
            ['_language' => 'en']);
    }

    private function clearTfaOnLogout(?string $userId, UserRepository $uR, UserInvRepository $uiR): void
    {
        $userInv = null !== $userId ? $uiR->repoUserInvUserIdquery((int) $userId) : null;
        if (null === $userInv) {
            return;
        }
        $user = $userInv->getUser();
        if (null === $user || $this->sR->getSetting('enable_tfa') !== '1' || !$user->is2FAEnabled()) {
            return;
        }
        $user->set2FAEnabled(false);
        // Securely clear TOTP secret
        $totpSecret = $user->getTotpSecret();
        $user->setTotpSecret('');
        $uR->save($user);
        // Clear secret from memory
        $this->secHelper->secureClearSensitiveData([&$totpSecret]);
    }
}
