on:
  pull_request:
    paths-ignore:
      - 'docs/**'
      - 'README.md'
      - 'CHANGELOG.md'
      - '.gitignore'
      - '.env.example'
      - '.gitattributes'
      - 'infection.json.dist'
      - 'psalm.xml'

  push:    
    branches: ['main']    
    paths-ignore:
      - 'docs/**'
      - 'README.md'
      - 'CHANGELOG.md'
      - '.gitignore'
      - '.env.example'
      - '.gitattributes'
      - 'infection.json.dist'
      - 'psalm.xml'

  schedule:
    - cron: '0 0 * * *'

name: invoice build

jobs:
  tests:
    name: PHP ${{ matrix.php }}-${{ matrix.os }}

    env:
      extensions: fileinfo, pdo, pdo_sqlite, intl, gd, openssl, dom, json, mbstring, curl, uopz
      
      # Framework/Core and should match src\Environment.php function prepare().
      # which is equivalent to a .env file
      
      # Local wamp lamp docker
      DOCK_AMP: docker
      
      # Application
      APP_C3: true
      APP_ENV: dev
      APP_DEBUG: true
      
      BUILD_DATABASE: false
      SENTRY_DSN: false
      BASE_URL: ""
      # Symfony Mailer
      SYMFONY_MAILER_USERNAME: "" 
      SYMFONY_MAILER_PASSWORD: "" 
      
      # OAuth2/Identity Providers (fill with example/test values from your .env)
      FACEBOOK_API_CLIENT_ID: "test_facebook_client_id"
      FACEBOOK_API_CLIENT_SECRET: "test_facebook_secret"
      FACEBOOK_API_CLIENT_RETURN_URL: "http://localhost/auth/facebook-return"
      GITHUB_API_CLIENT_ID: "test_github_client_id"
      GITHUB_API_CLIENT_SECRET: "test_github_secret"
      GITHUB_API_CLIENT_RETURN_URL: "http://localhost/auth/github-return"
      GOOGLE_API_CLIENT_ID: "test_google_client_id"
      GOOGLE_API_CLIENT_SECRET: "test_google_secret"
      GOOGLE_API_CLIENT_RETURN_URL: "http://localhost/auth/google-return"
      GOVUK_API_CLIENT_ID: "test_govuk_client_id"
      GOVUK_API_CLIENT_SECRET: "test_govuk_secret"
      GOVUK_API_CLIENT_RETURN_URL: "http://localhost/auth/govuk-return"
      LINKEDIN_API_CLIENT_ID: "test_linkedin_client_id"
      LINKEDIN_API_CLIENT_SECRET: "test_linkedin_secret"
      LINKEDIN_API_CLIENT_RETURN_URL: "http://localhost/auth/linkedin-return"
      MICROSOFTONLINE_API_CLIENT_ID: "test_msonline_client_id"
      MICROSOFTONLINE_API_CLIENT_SECRET: "test_msonline_secret"
      MICROSOFTONLINE_API_CLIENT_RETURN_URL: "http://localhost/auth/msonline-return"
      MICROSOFTONLINE_API_CLIENT_TENANT: "common"
      OPENBANKING_API_CLIENT_ID: "test_openbanking_client_id"
      OPENBANKING_API_CLIENT_SECRET: "test_openbanking_secret"
      OPENBANKING_API_CLIENT_RETURN_URL: "http://localhost/auth/openbanking-return"
      VKONTAKTE_API_CLIENT_ID: "test_vk_client_id"
      VKONTAKTE_API_CLIENT_SECRET: "test_vk_secret"
      VKONTAKTE_API_CLIENT_RETURN_URL: "http://localhost/auth/vk-return"
      X_API_CLIENT_ID: "test_x_client_id"
      X_API_CLIENT_SECRET: "test_x_secret"
      X_API_CLIENT_RETURN_URL: "http://localhost/auth/x-return"
      YANDEX_API_CLIENT_ID: "test_yandex_client_id"
      YANDEX_API_CLIENT_SECRET: "test_yandex_secret"
      YANDEX_API_CLIENT_RETURN_URL: "http://localhost/auth/yandex-return"  

    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest

        php:
          - 8.3
          - 8.4

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install PHP with extensions
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: ${{ env.extensions }}
          ini-values: date.timezone='UTC'
          tools: composer:v2
          coverage: pcov
          
      - name: Determine composer cache directory on Linux
        if: matrix.os == 'ubuntu-latest'
        run: echo "COMPOSER_CACHE_DIR=$(composer config cache-dir)" >> $GITHUB_ENV
        
      - name: Determine composer cache directory on Windows
        if: matrix.os == 'windows-latest'
        run: echo "COMPOSER_CACHE_DIR=~\AppData\Local\Composer" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
        
      - name: Cache dependencies installed with composer
        uses: actions/cache@v4
        with:
          path: ${{ env.COMPOSER_CACHE_DIR }}
          key: php${{ matrix.php }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: |
            php${{ matrix.php }}-composer-
            
      - name: Update composer
        run: composer self-update
        
      - name: Install dependencies with composer
        run: composer update --prefer-dist --no-interaction --no-progress --optimize-autoloader --ansi
                
      - name: Install dependencies with npm
        run: npm update