on:
  pull_request:
    paths-ignore:
      - 'docs/**'
      - 'README.md'
      - 'CHANGELOG.md'
      - '.gitignore'
      - '.env.example'
      - '.gitattributes'
      - 'phpunit.xml.dist'
      - 'psalm.xml'

  push:
    branches: ['main']  
    paths-ignore:
      - 'docs/**'
      - 'README.md'
      - 'CHANGELOG.md'
      - '.gitignore'
      - '.env.example'
      - '.gitattributes'
      - 'phpunit.xml.dist'
      - 'psalm.xml'

  schedule:
    - cron: '0 0 * * *'

name: invoice dependency checker

jobs:
  mutation:
    name: PHP ${{ matrix.php }}-${{ matrix.os }}
        
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os:
          - ubuntu-latest

        php:
          - 8.4
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6

      - name: Install PHP
        uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240 # v2
        with:
          php-version: ${{ matrix.php }}
          extensions: fileinfo, pdo, pdo_sqlite, intl, gd, openssl, dom, json, mbstring, curl, uopz, libxml
          tools: composer:v2, cs2pr
          coverage: none

      - name: Determine composer cache directory
        run: echo "COMPOSER_CACHE_DIR=$(composer config cache-dir)" >> $GITHUB_ENV

      - name: Cache dependencies installed with composer
        uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5
        with:
          path: ${{ env.COMPOSER_CACHE_DIR }}
          key: php${{ matrix.php }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: |
            php${{ matrix.php }}-composer-

      - name: Update composer
        run: composer self-update

      - name: Install maglnet/composer-require-checker
        run: composer require maglnet/composer-require-checker:^4.19

      - name: Check dependency
        run: vendor/bin/composer-require-checker
